### ISSUE TITLE
Add example prometheus setup

### ISSUE THREAD

**Issue by adriancole** [openzipkin/docker-zipkin#121]
To show how server metrics can be useful, it would be best to setup prometheus (or some other setup) accordingly. Otherwise, they can be a bit abstract.
- setup instructions https://github.com/openzipkin/zipkin/tree/master/zipkin-autoconfigure/metrics-prometheus#prometheus-metrics
- question about how metrics can be interpreted https://github.com/openzipkin/zipkin/issues/1318#issuecomment-250458125

cc @kristofa @klette @abesto @klingerf @gena01 for ideas, too

**Comment by BenHall** [comment]
I've been meaning to get in touch since your talk at OSCON Austin, I was impressed with Zipkin. I'm the founder of Katacoda, we're an interactive technical learning platform for software developers. We allow users to access production-like environments directly in their browser for learning and experimenting. 

With regard to the issue, would it be useful to have an interactive scenario on how Prometheus and Zipkin work together? The scenario could discuss configuring Prometheus and how Zipkin metrics can be pushed into it. It would be able to highlight the benefits and how it can be configured with a real-system. 

Here are two scenarios we collaborated on with other open source projects to highlight their initial use-case. More coming soon:
https://katacoda.com/courses/coredns
https://katacoda.com/courses/traefik

Would that help solve the problem? Long term, I was thinking additional scenarios could cover ES, MySQL etc

**Comment by adriancole** [comment]
Thanks for reaching out, Ben. This sounds like a neat way to learn. cc
@abesto

**Comment by abesto** [comment]
Huh. Agree, this looks interesting. I've recently played around with Prometheus, running it locally with a simple setup was trivial, so I think we could add it to a `docker-compose.yml` with minimal fuss. Adding this to my todo list, no commitment for now.

@BenHall, given that Zipkin already has support for exposing a Prometheus-compatible endpoint, I think a Zipkin-Prometheus specific scenario would provide significantly less value than a "Prometheus intro" scenario. Of course it'd make total sense to then build a Prometheus-Zipkin scenario on top of it.

**Comment by adriancole** [comment]
(on the training aside) actually agree w/ @abesto in hind-sight. we probably would get more bang for the buck adding to prometheus, or directing towards a generic zipkin one
