### ISSUE TITLE
Configurable metrics endpoints

### ISSUE THREAD

**Issue by NikolaeVarius** [openzipkin/docker-zipkin#178]
I am trying to get docker-zipkin to work with some custom parameters related to metrics. Aka map /metrics to dump prometheus metrics and /springmetrics to dump normal metrics

i was hoping that adding " -Dendpoints.prometheus.id=metrics -Dendpoints.metrics.id=springmetrics" to JAVA_OPTS env vars would work, but no dice.  Any advice on how to handle this?

**Comment by adriancole** [comment]
this probably should be on normal zipkin repo, better yet gitter

https://gitter.im/openzipkin/zipkin

but I think what you are looking for might have changed anyway.. zipkin is
now spring boot 2, so under the covers most things are under /actuator. we
re-mapped the endpoints that we explicitly documented also so that health
checks wouldn't break during the upgrade
