### ISSUE TITLE
Switch default storage to MySQL

### ISSUE THREAD

**Issue by adriancole** [openzipkin/docker-zipkin#61]
I think it is time we switch the default docker-compose file to mysql. The goal of docker-compose was our 5 minute story. MySQL is the fastest way to tell the story of zipkin, particularly as it has no setup required to show the Dependencies view.

I'm glad we have cassandra, as people may quickly outgrow mysql, but I feel we should put easiest as the first option forward.

**Comment by jfeltesse-mdsol** [comment]
:+1:

MySQL is far more widespread, making it easier for people to look "under the hood" if needs be.

**Comment by tangying123** [comment]
I want to save database . 
services:
  # Run MySQL instead of Cassandra
  storage:
    image: openzipkin/zipkin-mysql:1.3.0
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - /mysql/db:/mysql/data

but I don't start the mysql in the docker 
the error ：
2016-08-04  2:14:52 139712119463336 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2016-08-04  2:14:52 139711766694576 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1146: Table 'mysql.gtid_slave_pos' doesn't exist
2016-08-04  2:14:52 139712119463336 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
2016-08-04  2:14:52 139712119463336 [Note] Server socket created on IP: '::'.
2016-08-04  2:14:52 139712119463336 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist

I want to resolve this problem.
Thank you

**Comment by michaelsembwever** [comment]
> MySQL is far more widespread, making it easier for people to look "under the hood" if needs be.

What's under the hood though is not Zipkin.
If you want to run Zipkin in any serious environment you have to run it with Cassandra. So all that "looking under the hood" becomes a red-herring, not helpful.

The reason to use MySQL as the default storage is to ease to view Dependencies.
This is a temporary advantage, as we look into later versions of Cassandra which will be able to do Dependencies without the need for Spark.

**Comment by jfeltesse-mdsol** [comment]
@michaelsembwever did you just reply to a comment I left _10 months ago_? 😄 

@tangying123 you should probably open a separate issue

**Comment by adriancole** [comment]
Please open a separate issue for separate concerns. Also you are running an
older version of zipkin.. Always best to open issues against current.

**Comment by adriancole** [comment]
it is hard to diagnose dependencies issues with cassandra as people have to figure out what may or may not be up with the cron. I think we should go ahead and make the default docker-compose file mysql https://github.com/openzipkin/docker-zipkin/issues/112

**Comment by adriancole** [comment]
insanity is doing the same thing, but expecting different results. MySQL is the easiest for me to support new users with, and having the default be MySQL is far better than having them fail and then teach them how to run MySQL https://github.com/openzipkin/docker-zipkin/pull/113
